### PR TITLE
Use discord-rich-presence instead of discord-rpc

### PR DESCRIPTION
**Pull request by kittenchilly**
Basically a wrapper for the latter, makes things easier to develop.
Also updated all dependencies and all assets to the latest pokeclicker version.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
I don't really see the point in swapping to `discord-rich-presence`, it doesn't really make anything easier/better and is just another dependency,

**Comment by kittenchilly** [comment]
discord-rich-presence replaces discord-rpc as a dependency.

**Comment by RedSparr0w** [comment]
It doesn't replace it as it's just a wrapper for it.

As it depends on `discord-rpc` this means `discord-rpc` is still a dependency in the project and will also lag behind on any updates `discord-rpc` has as `discord-rich-presence` would need to be updated after.

**Comment by kittenchilly** [comment]
When looking around, I've noticed a lot of electron apps use discord-rich-presence over discord-rpc. It does actually simplify the code, and it'd be easier to develop for whenever we want to do more with our rich presence support

**Comment by RedSparr0w** [comment]
IMO it doesn't really simplify or make anything easier in terms of development and I would rather not change over to using it,
If you could revert that, everything else in the PR looks fine to me.

**Pull request closed without merging**
